name: CD - Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - "FinSolve.IDP.Functions/**"
      - "FinSolve.IDP.Application/**"
      - "FinSolve.IDP.Domain/**"
      - "FinSolve.IDP.Infrastructure/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish Functions project
        run: dotnet publish FinSolve.IDP.Functions/FinSolve.IDP.Functions.csproj -c Release -o published

      - name: Deploy to Azure Function App
        run: |
          az functionapp deploy \
            --resource-group ${{ secrets.AZURE_RG }} \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --src-path published \
            --type zip
