name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infrastructure/main.bicep"
      - "infrastructure/modules/**"
      - "infrastructure/parameters/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep to Azure
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: infrastructure/main.bicep
          parameters: infrastructure/parameters/${{ secrets.ENVIRONMENT }}.json
          failOnStdErr: false
